### ISSUE TITLE
Light control triggers

### ISSUE THREAD

**Issue by RedKrieg** [vchlum/hue-lights#1]
Is it possible to detect when a new notification is created?  I would love to be able to have one or more of my bulbs blink and/or change color when a notification arrives.

I really like your extension, simple and useful.

**Comment by vchlum** [comment]
Hi @RedKrieg , thank you for the suggestion. I like your idea. I will look into it, can't promise it right now. I did fast research, and it should be possible. I will let you know here. Stay tuned.

**Comment by vchlum** [comment]
Hi @RedKrieg, version 5 is available on e.g.o with lights notification support. The selected lights blink for 1 second when the notification is created. You can choose the color and brightness of the lights.

**Comment by RedKrieg** [comment]
It works perfectly for my hue bulbs!  I thought it wasn't working at first because the hue strip I selected wasn't changing, but it seems like the hue strip problem affects changing color in the entire application, so I'll open a different issue for that once I do a bit of research.  Thank you for this feature, it's exactly what I wanted!
