### ISSUE TITLE
Feature:  Automatically turn on/off with the program.

### ISSUE THREAD

**Issue by Cartas** [vchlum/hue-lights#10]
_Not sure if you take requests like this, so close immediately if not._ 

Firstly - what an amazing extension!  :sparkling_heart: 

The only feature I can imagine being added to improve this already amazin' extension even further would be the ability to have a light sync with the starting and stopping of the extension.  When I turn on my computer and this extension loads it would turn on a chosen light, and similarly when I shut down my computer and the extension closes it would turn this light off.

Is this even a programmatic possibility?

**Comment by vchlum** [comment]
Hi @Cartas,

Thank you for the idea.

The gnome extensions are **enabled** on login/wakeup/screen unlock and **disabled** on logout/sleep/screen lock. So these events could be used for your request. It would mean that selected light(s) would be turned off even on a simple screen lock. Does it sound good to you?

I will think this through. Maybe, I would consider a more general feature. Right now, it is possible to blink on notify. This feature could be redesigned to be able to run tasks on events.  Like, run turnon/turnoff/blink on enable/disable/notify/... and more events/tasks could be added in the future.

**Comment by Cartas** [comment]
Thanks for the quick response!

Sounds like it triggering with screen locking and unlocking makes it even better!  :tada:

**Comment by vchlum** [comment]
Hi @Cartas or anybody else!

I am afraid I have bad news regarding this feature. I have implemented the first version of the feature and hit an issue. Turning light on on login works as expected, but turning light off on logout/shutdown/... behaves oddly.

Gnome-shell provides the function disable(). This function should be [called on logout, shutdown, or screenlock](https://wiki.gnome.org/Projects/GnomeShell/Extensions/Writing#extension.js_.28Required.29). AFAIK it is the only suitable place how to hook such an event. I wanted to add a hook for calling the action like 'lights off' in this function. For me, the function seems to be called only on locking the screen (Fedora 33). I checked [StackOverflow](https://stackoverflow.com/questions/15614120/gnome-shell-extension-destructor-run-on-gnome-shell-exit) and it seems like the function is not consistently called on all distributions or all versions of gnome-shell.

Without consistent behavior, I do not want to add the feature anyway. But If anybody knows the reason or how to fix I will be happy to resume the work on this feature.

**Comment by Cartas** [comment]
Ah, that's a real shame. My apologies for getting you to spend your time on something that isn't seemingly possible! 😳

Thank you ever so much regardless! ❤️

**Comment by vchlum** [comment]
Hi, @Cartas once again! I have a slightly different solution for you.

In version 9 of this extension, the support for entertainment areas has been added. In the recent commit, autostart of an entertainment area has been added.

If you have Philips Hue branded bulbs and light strips, you can create an entertainment area in your mobile app. The entertainment area has the attribute "behavior when sync stops" and you can set this attribute to "Off". Now, if the sync would be inactive for 10 seconds, it will turn off the lights in the active entertainment area. This will substitute the missing call of the disabling event. (If the event is called, the entertainment area is disabled immediately)

If you like to test it, you can manually install the version from the main branch, or you can wait for version 10 on e.g.o.

As a side effect, some CPU utilization can be noticed - depends on the level of sync intensity (and for mode 'sync screen' also depends on the number of lights).

**Comment by Cartas** [comment]
Wow, that sounds amazing!   Eagerly lookin' forward to givin' it a whirl when v10 comes out.

Thanks for the hard work and actually looking into my request :pray:

**Comment by vchlum** [comment]
Version 10 is out for few days. Please let me know. Do you have more thoughts/ideas on this topic?

**Comment by vchlum** [comment]
Similar feature added, resolved.

**Comment by Cartas** [comment]
@vchlum Ah, my apologies for missin' this completely!  :cold_sweat: 

That's great news - thank you ever so much for the hard work and implementation!  It works delightfully!  :tada:
