### ISSUE TITLE
Amazing work, could it be ported to Windows?

### ISSUE THREAD

**Issue by dferrandizmont** [vchlum/hue-lights#11]
Just to say that this extensions is awesome, really good work @vchlum, love it on my Ubuntu, but I'm using it only for work and I would love to use it on Windows too, any chances to do one for it?

**Comment by vchlum** [comment]
Hi @dferrandizmont ! I am afraid I do not use Windows. Moreover, I think javascript is not a very suitable language for windows desktop applications. Javascript would need some additional framework on Windows. This project is really intended only as a Gnome extension and to port it to Windows is IMHO not feasible. It would mean starting a new project. 

I am glad you like this extension and I am sorry not to have better news.

**Comment by dferrandizmont** [comment]
No worries about not being able to port it to Windows, was more like a dream haha, I really like it so just thank you for this amazing work anyway! :100:
