### ISSUE TITLE
Use gnome default icon for refresh / sync

### ISSUE THREAD

**Issue by 2nv2u** [vchlum/hue-lights#12]
Hi, i would suggest using the default icon for the refresh option

https://github.com/vchlum/hue-lights/blob/23dce50ae6ab0d21da1ce9843a29f6570023cebe/extensionmenu.js#L2417

`new Gio.ThemedIcon({ name: 'emblem-synchronizing-symbolic' })`

**Comment by vchlum** [comment]
Hi @2nv2u . I agree. Thank you. I will change it.

**Comment by 2nv2u** [comment]
Np! Nice plugin in itself btw, appreciated!
