### ISSUE TITLE
Remove settings button

### ISSUE THREAD

**Issue by 2nv2u** [vchlum/hue-lights#13]
Hi, I would suggest removing the settings button.
This already exists in the extension configuration and is only for setup purposes, it clutters the menu itself now.

**Comment by vchlum** [comment]
Hi @2nv2u , thank you for the suggestion. Maybe this item could be there only if a bridge is not connected? What do you think? Would it be too confusing? ...or, and I like it, I could add an option into the setting for hiding the setting item in the menu. So it would be optional but visible by default.

My concern is whether the setting is easily available in all distros. Of course, you have a few options on how to access the settings. You can access the setting on the e.g.o. page, using the 'gnome-extensions prefs' command or using the optional tweak utility. IMHO the tweak utility is the most convenient, but not everybody has this utility installed.

**Comment by 2nv2u** [comment]
Gnome has an extensions app, not sure if it's default in all distributions though.
Having a setup / settings option could be an nice idea.
Creating a setting out of it in the settings itself would to me feel too much, less is always more.

Maybe if you have a look at my UI idea that might give it a unobtrusive place.

**Comment by vchlum** [comment]
I use Fedora and the extension app is not installed by default. So I would not count on it.

Let's go with the settings item to be visible only without an available bridge. ...or redesigning the UI.

**Comment by 2nv2u** [comment]
Another option is to just let is be of course.. ;)

I do think it's however it's an option which becomes pretty much of no use after the initial setup has been done.
Maybe if no config is there just show a setup / configure menu item and open the settings dialog immediately.
If you would chance the UI in a similar way as I described in the other thread, the settings could go in the bridge sub menu for later use.

**Comment by vchlum** [comment]
I like something like this:
![Snímek z 2021-03-29 21-47-48](https://user-images.githubusercontent.com/16756616/112891729-c5c09380-90d8-11eb-8590-2df38f6df2d7.png)

If no bridge is connected the settings can have a full menu item in the menu. This small icon would be shown with at least one bridge connected.

Your thoughts?

**Comment by 2nv2u** [comment]
I would clean it up a bit already yes, but me personally would just remove them completely, they don't serve any purpose in normal use. Maybe this can be a solution for now and, if you are interested we could pursue, the other UI ticket further.

**Comment by vchlum** [comment]
resolved, for now, it will be changed with #14
