### ISSUE TITLE
Since version 10 unlocking session turns on entertainment mode

### ISSUE THREAD

**Issue by RedKrieg** [vchlum/hue-lights#15]
Every morning when I log in, entertainment mode gets enabled (I have only manually enabled it once in the past) and I have to go through a process of refreshing the tray and deactivating entertainment mode multiple times before it will finally let me use my lights normally.  How can I gather more info about this to help troubleshoot?

**Comment by vchlum** [comment]
Hi @RedKrieg! Please, check the Settings and the tab "Entertainment areas". There is a new setting possible: "Autostart entertainment area". Select "none". If "none" is already selected, we will investigate.

If more investigation is needed, please enable "log debug messages" on the tab "Advanced settings" and run `dbus-run-session -- gnome-shell --nested --wayland 2>&1 | grep -i hue -C 5 > hue-lights.log` If the trouble is only after startup you can than close the window and provide the log, please. Do not forget to disable the debug messages afterwards.

**Comment by RedKrieg** [comment]
Hi @vchlum sorry I didn't see that new setting.  Setting it to "none" resolved the issue for me!  Is it set to a room by default when upgrading or did I somehow set that and not realize it?
