### ISSUE TITLE
Can't switch off entertaiment area after adding the area without relogin

### ISSUE THREAD

**Issue by cm-t** [vchlum/hue-lights#17]
Hi,

Thank you for your work on this awesome extension !

# my setting 

(everything is fine, i have succesfuly removed and readded my bridge to make entertainment works) I just set up a new extension area names "Cinema-t":
 * ![image](https://user-images.githubusercontent.com/2675615/115870462-91be6100-a43f-11eb-9620-dd95e0491cac.png)

# Description 
When I click on this button:
![image](https://user-images.githubusercontent.com/2675615/115870536-ab5fa880-a43f-11eb-8634-a71adca3ef87.png)

## Expected result:
 * ![image](https://user-images.githubusercontent.com/2675615/115870680-de09a100-a43f-11eb-841b-fd21016f918d.png)
 * The screen sync (or whatever effect choosen) goes off
 * So i can apply a scene for exemple, or soft switch off the lights
 * 
## Current result:
 * ![image](https://user-images.githubusercontent.com/2675615/115870555-b0bcf300-a43f-11eb-9a9a-a759a62f1194.png)
 * The screen sync is still on
 * I can't change scene or soft switch off lights

**Comment by cm-t** [comment]
I think all of this was launched by this:

![image](https://user-images.githubusercontent.com/2675615/115871896-6ccaed80-a441-11eb-9031-9d1f89f91db6.png)

I now try with 

![image](https://user-images.githubusercontent.com/2675615/115871946-810eea80-a441-11eb-8395-6e2a6787a5c8.png)

and let you know asap (brb 30 sec to relog on)

**Comment by vchlum** [comment]
Thank you @cm-t for your exhausting report. Unfortunately, I wasn't able to reproduce it yet.

IMHO, between those two steps:
 * in the entertainement tabs i select sync screen and Cinema-t
 * a notification tells me to unpaire and pair it again

I would expect an important middle step... Selecting the entertainment area on the entertainment tab should not invoke the notification.

I was able to find and fix a bug in the code, that could cause the issue you have described. The bug I discovered could work regardless of the settings in the entertainment tab. I can not verify the fix fixes your issue. I do not consider this issue to be fixed, I will investigate more.

In case you would be able to reproduce the error, please enable the logging of debug messages on the tab advanced and try to enable/disable the sync. The debug msgs will be stored in the gnome-shell log.

**Comment by cm-t** [comment]
You are probably right for the middle step, i was just trying to remember the steps at a moment i didn't know i should remember it.

As you said, if I can reproduce it again, I will enable the log !

Thank you

**Comment by vchlum** [comment]
I found and fixed the issue. The trouble was in getting stuck in the 'starting' state of synchronization with the entertainment area autostart enabled.

**Comment by vchlum** [comment]
Resolved.
