### ISSUE TITLE
Sync screen does not seem to work on my device

### ISSUE THREAD

**Issue by ThePolyknight** [vchlum/hue-lights#18]
Hi there,

this is a realy great extension but i have some issues here:

### **Desccription**

When i click on the button "Arbeitszimmer" to sync my Hue light devices to my desctop it will do nothing.
The button deactivates after a few seconds:

![Bildschirmfoto vom 2021-05-02 19-02-46](https://user-images.githubusercontent.com/51757992/116821338-cfc32f80-ab79-11eb-942a-0a0f6c73916a.png)

I reconnected the Hue bridge a few times but nothing changed.
I also tested to create a new entertainment area without any success.

### **My system**

OS: Manjaro Linux x86_64 
Kernel: 5.12.0-1-MANJARO 
GNOME Version: 3.38.4 (neofetch); 40.0.0 (Settings)?
Window manager: X11
Hue-lights Version: 12

**Comment by vchlum** [comment]
Hi @ThePolyknight ,

Just tested the sync screen on a fresh install of Manjaro and it works.

Do other modes work OK (like track cursor or random)? Is the problem with the sync screen only? If this is only a sync screen problem, do you have multiple displays? If yes, do they make a solid rectangle? E.g.: this screen will not work:
![not-solid-square-screen](https://user-images.githubusercontent.com/16756616/116849356-e2c41700-abee-11eb-8307-6845cfe75919.png)
If this is the case, a notification should be displayed, that your screen is not a solid rectangle and the sync will not start.

If your screen is a solid rectangle, please enable debug log messages in settings on tab 'advanced settings'. With the debug messages enabled, run this command `journalctl -f /usr/bin/gnome-shell > gnome-shell.log`. Try to start the sync screen, and wait for the failure so the actions are caught on the log file. Please, provide the log afterwards.

Btw: I can see you are using a bright theme. Did you know you can switch to the dark icon pack in the settings? So, your icons will be visible...

**Comment by ThePolyknight** [comment]
Hi @vchlum,

Track cursor mode or random mode do also not work on my system.
I do have two screens but they do a solid rectangle.

I did run the command.
Here is the log file:

[gnome-shell.log](https://github.com/vchlum/hue-lights/files/6417356/gnome-shell.log)

Additionaly I provide a list of all my enabled gnome extensions here:

![Bildschirmfoto vom 2021-05-03 21-19-44](https://user-images.githubusercontent.com/51757992/116922631-ee96f400-ac55-11eb-9257-15b581a12f83.png)
![Bildschirmfoto vom 2021-05-03 21-20-31](https://user-images.githubusercontent.com/51757992/116922644-f191e480-ac55-11eb-87a8-1fafb04ed050.png)

Im using the extension Night Theme Switcher.
So at this time my theme was set to light mode.
But I will change the cursor theme so I can see my icons.

Thank you for your help!

**Comment by vchlum** [comment]
Could you please:
 * run command: `dconf reset /org/gnome/shell/extensions/hue-lights/entertainment`
 * log out
 * log in
 * do not open settings
 * try again

I can see some invalid values in this key.

**Comment by ThePolyknight** [comment]
Hey @vchlum,

sorry for the late respond.
This also doesnt do the trick.

The sync mode will still deactivate itself.
I send you the new lof file after i did run the command:

[gnome-shell.log](https://github.com/vchlum/hue-lights/files/6436358/gnome-shell.log)

**Comment by vchlum** [comment]
I also tried sync the screen on a fresh live boot usb of manjaro. No issues here (manjaro-gnome-21.0.4-minimal-210506-linux510).

I suspect some issues in your local network. Your second log doesn't seem to try to start the entertainment area. Did you try to enable the sync?

The communication for syncing uses UDP, port 2100. Based on your first log, the first message is sent and the first response is received, but the second message is without response. UDP packet could be lost but IMHO the bridge expects the second message and if the second message is not received by the bridge, the bridge will send the first msg again. I can not see it in the log.

Please, try the following command:
`sudo tcpdump -n udp port 2100 -v -X > hue-lights_udpdump.log`
and once it will display "listening on", please try to start the sync exactly once and provide the log.

Also please check the setting of your router. Not sure, what could be wrong.

**Comment by cfpandrade** [comment]
> Hi @ThePolyknight ,
> 
> Just tested the sync screen on a fresh install of Manjaro and it works.
> 
> Do other modes work OK (like track cursor or random)? Is the problem with the sync screen only? If this is only a sync screen problem, do you have multiple displays? If yes, do they make a solid rectangle? E.g.: this screen will not work:
> ![not-solid-square-screen](https://user-images.githubusercontent.com/16756616/116849356-e2c41700-abee-11eb-8307-6845cfe75919.png)
> If this is the case, a notification should be displayed, that your screen is not a solid rectangle and the sync will not start.
> 
> If your screen is a solid rectangle, please enable debug log messages in settings on tab 'advanced settings'. With the debug messages enabled, run this command `journalctl -f /usr/bin/gnome-shell > gnome-shell.log`. Try to start the sync screen, and wait for the failure so the actions are caught on the log file. Please, provide the log afterwards.
> 
> Btw: I can see you are using a bright theme. Did you know you can switch to the dark icon pack in the settings? So, your icons will be visible...

I have a similar setup, 2 screens where they are not a rectangle, is there a way to choose sync with only 1 screen or a workaround for this?

**Comment by vchlum** [comment]
@cfpandrade Not yet. There is already an issue #23 filed for that. I can not say you the ETA but I would like to add the screen selection.

**Comment by vchlum** [comment]
@ThePolyknight I will close this as you haven't responded for a long time. If you wish to resume the investigation of your issue, please let me know.

@cfpandrade. The display selection has been added.
