### ISSUE TITLE
Sync does not work in fullscreen playback

### ISSUE THREAD

**Issue by Dan-RAI** [vchlum/hue-lights#20]
The sync stops on switching to fullscreen playback of embedded video in chrome ( for instance youtube)

**Comment by vchlum** [comment]
Hi, do you use a video with black borders? What is your screen ratio? Maybe this is the same issue as in #19 . Could you please try a video without black borders? E.g.: https://www.youtube.com/watch?v=H31Rl3PeS3s&ab_channel=HeadofSoftwareLab.

**Comment by Dan-RAI** [comment]
Hm, I think its the black borders. Your video doesn't work either, as my resolution is 3840x1600, and so most videos have black borders. Widescreen videos like  https://www.youtube.com/watch?v=JH_BAwSFKwM work. 

Seems like one has to add some smart way to detect the resolution of the active playback.

**Comment by vchlum** [comment]
That would be it. Thank you for verifying. Stay tuned for #19. It will resolve your issue too.

**Comment by vchlum** [comment]
@Dan-RAI You can use a shortcut SUPER+ATL+a during full-screen video playing and select a screen area for syncing, but first you need to set an entertainment area for the synchronization. See the menu.

**Comment by TheBubblePopped** [comment]
1920 x 1080 here. While running VLC with no boarders it stops syncing as soon as the play bar drops down to hide itself.
