### ISSUE TITLE
Pressing refresh button freezes the entire desktop

### ISSUE THREAD

**Issue by slrtbtfs** [vchlum/hue-lights#25]
When the bridge has been disconnected, the extension menu offers a "Refesh" button instead of a List of Lights/Rooms/Zones/etc.

Pressing that button sometimes freezes the entire desktop and keyboard and mouse input seem to no longer have any effect, not even allowing to switch to a tty. Non graphics related stuff like audio and network connections continue to work, though,

**Comment by slrtbtfs** [comment]
Hi,

thanks for the quick reply!

> Once the desktop is frozen, it will never come back to life?

No. I've even tried letting it run for an hour or so once, without success. Since other applications, like a web browser playing audio, continue to run I suspect that some kind of main loop in gnome shell might be blocked by the extension.

> If this happens, is it e.g. possible that some other device uses the same IP address as your bridge (e.g. due to being in a different local network)?

I'm only connected to one local network with that IP address, so this shouldn't happen.

However, my laptop has multiple network cards (Ethernet and WiFi) that are connected to this network. Usually, before the freeze happens, at least one of those had been disconnected, e.g. by suspending the laptop or removing it from the desk.

I'll try to collect logs, the next time this happens.

**Comment by slrtbtfs** [comment]
I just found something that might confirm the main loop hypothesis.

* Set up a hue bridge
* Start up glxgears or something else that shows a smooth animation
* Click the "Refresh Menu" button in the extension menu, while watching the animation.
* While the menu refreshes, the animation freezes for about half a second.

If the refresh procedure somehow gets stuck, it seems plausible that the desktop never unfreezes.

**Comment by slrtbtfs** [comment]
Thanks!

Once the desktop no longer freezes it will at least be easier to debug the failed menu refresh.

**Comment by vchlum** [comment]
Hi @slrtbtfs, could you please test the latest version on the main branch? I had no luck freezing the desktop. I believe the latest version should not freeze your desktop. I am afraid of not having a response from the IP (good, bad, unknown, or anything) no items in the menu will be built.  I am afraid this happens to you. The items are built once any response from all bridges is known.

One more question, the default connection timeout is 2 seconds (see advanced menu). Did you e.g. change it?

**Comment by slrtbtfs** [comment]
Thanks for the quick fix!

> Hi @slrtbtfs, could you please test the latest version on the main branch? I had no luck freezing the desktop. I believe the latest version should not freeze your desktop. 

I can confirm it no longer freezes my desktop, which is great. Even glxgears didn't glitch. Instead it simply doesn't build a menu when no  bridge is reachable. So i guess this issue is fixed.

> I am afraid of not having a response from the IP (good, bad, unknown, or anything) no items in the menu will be built. I am afraid this happens to you.

It appears, when the freezes used to happen, the bridge was indeed unreachable, most likely due to kernel driver or hardware issues. It turns out that other applications that try to access the network interface providing a route to the bridge in that situation eventually start hanging as well, but without bringing down the entire desktop environment.

>  The items are built once any response from all bridges is known.

Unrelated: Wouldn't it make more sense to build a UI even when only some of the bridges respond? This might be useful for portable devices used in multiple households, each which its own bridge.

> One more question, the default connection timeout is 2 seconds (see advanced menu). Did you e.g. change it?

No this setting was unchanged.

**Comment by vchlum** [comment]
Thank you for your confirmation. I will fix the no-menu issue. It will always show at least the refresh and settings items.

> Unrelated: Wouldn't it make more sense to build a UI even when only some of the bridges respond? This might be useful for portable devices used in multiple households, each which its own bridge.

Of course, it is not needed to have all the bridges up and running. Basically, I meant I need at least information about  (un)availability from all bridges. This need is because of knowing how many bridges are up, and how many bridges should be included in the menu.
