### ISSUE TITLE
Notification triggers Phillips Wall Switch Module unprompted

### ISSUE THREAD

**Issue by jonathanballs** [vchlum/hue-lights#26]
Hello,

I have been using the hue-lights GNOME extension for a while now with great success. It's been an enjoyable experience for me! Recently I purchased a [Phillips Wall Switch Module](https://www.philips-hue.com/en-gb/p/hue-philips-hue-wall-switch-module/8719514318045) so that my light switches can be intelligent too. You can see it in the screenshot below - it registers as 'Jonny's Room Light Switch' in the UI.

![Screenshot from 2021-09-06 19-43-49](https://user-images.githubusercontent.com/4366510/132253585-476e84db-fcbe-44e1-bfe8-db2120324dad.png)

The enabling/disabling of the switch works well as does the battery light indicator however I believe that hue-lights and the switch may have some incompatibilities. Since installing the switch I have noticed that the light will turn *on* randomly - it doesn't turn off randomly though. I have also noticed occasionly that it will change colour very rapidly to very white light and then to a normal softer light. Sometimes it does this while I am actually using the menu other times it is random. I disabled the extension and it stopped happening. I turn my computer off at night and it has stopped happening.

I have not found a reliable way to reproduce this but I suspect that the extension is communicating the switch by trying to get information and is causing it to behave unexpectedly. I understand that you may not have this wall switch module to test with so I would be happy to provide any assistance to get this fixed. If you can point me to the right part of the code I may even be able to help fix it!

**Comment by vchlum** [comment]
Hi @jonathanballs ! Thank you for filing the issue. I indeed do not own the Wall Switch Module, but let's try to debug it together:-)

First, I would like to ask whether the  'Jonny's Room Light Switch' is only available in the 'Philips hue' bridge submenu as shown in the screenshot. This submenu should not control the device - this is only for disabling/enabling the whole device, and also the battery status is shown. The controlling itself should be available within the group 'Jonny's Room'. Is it there? Is it possible to control the switch at all (with this extension)?

In the title, you have mentioned that the notification triggers the switch. Please, check the settings of the extension. Go to "General settings" and check whether the 'Jonny's Room Light Switch' is checked within the 'Notification lights'. Is this related to your issue?

Anyway, please go to "Advanced settings" and enable "Log debug messages". After this, open the terminal and run the command:  `journalctl -f | grep -i hue`, and with the command running, please try some light control. You should see something like the following line:
`gnome-shell[3100]: Hue Lights (debug): Bridge GET request, url: http://192.168.1.119/api/GVTIvweTtFVt9--9FllAUdiGj1HYG9BMegQWOi0K/ data: null`
Please, open the link which looks like:
`http://192.168.1.119/api/GVTIvweTtFVt9--9FllAUdiGj1HYG9BMegQWOi0K/ `
in your local browser. You should see JSON output containing the bridge data. I see two options, you could either share all the data or please search the data and provide all sub dictionaries with the occurrence of 'Jonny's Room Light Switch' (with the path in the JSON dictionary).

I expect to see the  'Jonny's Room Light Switch' in the "sensors" section and probably in the "lights" section, and I hope I will see some hint to this issue in this data.

**Comment by vchlum** [comment]
Hi again! I looked into how the Philips Hue Wall Switch works, and it only pushes the bridge to turn on/off the Philips Hue bulb based on pressing the original wall switch.

From that, I think the extension can not control the  Philips Hue Wall Switch. (Besides enabling/disabling it) I suppose you have selected the bulb that is controlled by your Philips Hue Wall Switch as the notification light in the settings, but the bulb should only blink on the notification. Hmm, hmm... I have no other idea yet.

It also means the 'Jonny's Room Light Switch' should be present only in the "sensors" section and not in the "lights" section of JSON output.

I am considering buying the device:-)

**Comment by jonathanballs** [comment]
Hi vchlum - sorry for not getting back to you! You were right and it seemed that I had connected my light to my notifications by accident. I think that it was just a coincidence that it started happening when I bought the wall switch module. So basically I think there was no bug - it was just a misconfiguration by myself!
