### ISSUE TITLE
sync audio

### ISSUE THREAD

**Issue by keeganstothert** [vchlum/hue-lights#27]
love this thanks!

would also be great to sync audio as with the hue entertainment app

**Comment by vchlum** [comment]
Hi! Thank you for the idea. Unfortunately, I already tried to add the feature, and I wasn't able to find a way how to read the audio stream in the gnome extension. I will look into it again.

If anybody has an idea how to accomplish this, please, share your knowledge:-)

**Comment by vchlum** [comment]
Audio sync added. Coming to the Gnome 45 release version soon.
