### ISSUE TITLE
Could this be made to work also with Ikea Tradfri?

### ISSUE THREAD

**Issue by lwbt** [vchlum/hue-lights#3]
Type: Wishlist/Suggestion

Could this be made to work also with an Ikea Tradfri gateway on the network? I now realize that the difference between hue and tradfri is or was that tradfri didn't have an API for developers to tinker with but researching this a bit, it seems like people have started hacking on this topic already.

(Yes I understand that it might be out of scope for this project when it is named hue lights and not tradfri or zigbee lights.)

**Comment by vchlum** [comment]
Hi @lwbt, thank you for your idea. Unfortunately, I suppose I will disappoint you. ....at least if I would answer right now.
 * Yes, it is kind of out of scope.
 * I do not have Tradfri gateway.

I will do some research concerning the Tradfri API/or whatever is available for it... I did not read about it yet, but I am aware there are apps that support both platforms.

Vaclav

**Comment by mslinn** [comment]
IKEA Trafri is really popular, I have a big investment in those bulbs and gateways.

**Comment by vchlum** [comment]
I am sorry, this request is for starting another project. I do not have Ikea devices - I can not support them.

**Comment by vchlum** [comment]
Hi!  I released a new extension and it also supports Ikea Dirigera. If you are interested, check out: https://extensions.gnome.org/extension/7737/smart-home/
