### ISSUE TITLE
Hide Icon When Unable to Connect

### ISSUE THREAD

**Issue by dav-is** [vchlum/hue-lights#33]
Whenever I'm using my laptop away from home, I get a notification saying it was unable to connect to my hue sync box. This isn't useful and it a bit annoying. I'd like an option to disable this notification.

Additionally, it'd be nice to hide the icon in the status bar when it can't connect (as I'm likely not home and it's not expected to work).

Maybe this could be smarter and whitelist certain ethernet and wifi networks to attempt connection.

**Comment by vchlum** [comment]
Agreed. I will improve this behavior.

**Comment by vchlum** [comment]
I looked into it and...

I think I could associate each device (device means a bridge or a sync box) to a network and save the association. The association would be dynamically changeable as the device can change the network too... ?? (e.g. potential multiple wifi networks in the same home). Simply, it doesn't hurt to save the association once a 'network <-> device' is connected and working.

The **notification** for a particular device would be displayed only if the extension instance (like a notebook or even pc) is connected with an associated network.

The **sync box icon** would be displayed only if the network associated with some sync box is connected.

The question is whether to hide the **main extension icon** (the bridge menu) too. I believe it could be hidden too. I can hook the refresh extension routine to the network device change thus once a network device is (re)connected I could check whether it is an interesting device to show the icon(s)... 

This behavior would be active only if any device is paired with this extension. So if no device is paired, the main icon would be displayed anyway.

With a device associated, you would have hidden icons (and disabled notifications) on unknown networks, thus the settings would be accessible only by gnome native possibilities. Not via the menu.

This solution could simply satisfy also the request from #14:
>Possible default bridge on wifi connection.

Sounds good? Do you have any more thoughts?

**Comment by dav-is** [comment]
Sometimes I connect my laptop via ethernet, and sometimes I connect over wifi. So allowing multiple networks to be tied to one device would be nice.

> The question is whether to hide the main extension icon (the bridge menu) too. 
I think that would be ideal.

**Comment by vchlum** [comment]
Done. Since version 16, you can associate each device with one or more networks. The smart discovering of associated networks is not implemented. It is more reliable and simply good enough to select the networks in settings if you want...
