### ISSUE TITLE
Add option to turn of notifications

### ISSUE THREAD

**Issue by markac** [vchlum/hue-lights#37]
My notifications panel is filled with "Please check the connection to Philips Hue bridge." and "Connection to Philips Hue bridge restored" when I switch between wired and wireless networks. 

Please could there be an option to disable notifications or have a single notification. Maybe change the icon rather than generating a notification.

Thanks

**Comment by vchlum** [comment]
Hi @markac ! Please upgrade the extension to the latest version. The notification has been removed in version 18 (issue #35).

**Comment by markac** [comment]
Hi @vchlum. Thanks for the quick update. I've just upgraded and the notification is gone. Thanks!
