### ISSUE TITLE
Screen sync only works sometimes

### ISSUE THREAD

**Issue by WillZeeee** [vchlum/hue-lights#39]
I'm running Zorin OS 16 and when I try to start screen sync it only works about 1 out of 20 times. When i switch it to on no lights starts syncing and if i leave it for about a minute the setting turns of by itself again. If I try to turn it of manually the bridge shows up as disconnected. The 1 out of 20 times when it does work it works for about 10 minutes or so before crashing and all the lights stops syncing and gets stuck on the color they were on. I have tried this with just 1 light and the maximum 10 lights with the same results. Not sure if this is an isolated issue for me or if it can be recreated. Might just have to change distro.

**Comment by vchlum** [comment]
Hi @WillZeeee !

First, try to reboot your bridge. Do synchronization from the original hue app works? E.g.: the Spotify sync?

Anyway, seems like an unstable connection to me... not sure. The sync screen uses UDP stream and if there is no data on the bridge for 10 seconds the stream goes automatically off. Please check your router for UDP issues.

Please, provide also the debug log. Go to Settings/Advanced and turn on debug messages. After that, check the extension is connected to the bridge and run this command:
`journalctl -f /usr/bin/gnome-shell 2>&1 | grep -i hue > hue-lights.log`
While the command is running start the sync screen, wait for the error, and upload the log.

I hardly doubt switching the distro would help, but I will test your distro in my VirtualBox...

**Comment by WillZeeee** [comment]
I have tried to reboot the bridge many times after trying different fixes on my own bit that did not get me anywhere. I'm considering maybe I have a defective bridge at this point. I don't have Spotify so I cant test that but I did boot up my old windows laptop and everything worked fine from there. Both screen and music sync.

I don't know exactly how to check for UDP issues in my router but I'm looking into it at the moment.

Here is the log you asked for. I first started the sync and let it time out by itself and after that is started it again and turned it off manually and as before the bridge got disconnected.
[hue-lights.log](https://github.com/vchlum/hue-lights/files/7900309/hue-lights.log)

**Comment by vchlum** [comment]
Thank you. This is not an issue with your bridge... I can reproduce. I will investigate. Please, be patient.

**Comment by yodatak** [comment]
Same error for me i can do some test if you want too

**Comment by vchlum** [comment]
Fixed, new release soon.
