### ISSUE TITLE
TypeError: ExtensionUtils.getSettings is not a function

### ISSUE THREAD

**Issue by DroWnThePoor** [vchlum/hue-lights#40]
I performed a manual installation on Gnome Shell 3.28.4 and the extension shows the "error/info" icon in Gnome Tweaks.
I am on Ubuntu 18.04, and trying to open settings shows this error trace:

TypeError: ExtensionUtils.getSettings is not a function

```
Stack trace:
  @/home/drown/.local/share/gnome-shell/extensions/hue-lights@chlumskyvaclav.gmail.com/utils.js:68:20
  @/home/drown/.local/share/gnome-shell/extensions/hue-lights@chlumskyvaclav.gmail.com/prefs.js:41:7
  _getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:75:13
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:90:31
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:243:17
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:397:5
  @<main>:1:43
```
I noticed that on the extensions.gnome.org auto install interface the Shell version list was newer shells than mine, but here on the Github I didn't see a mention of a minimum Gnome-Shell version so I figured it was worth a go, but maybe that is the case.
Please let me know either way.
Also, is there an alternative for Philips-Hue aside from your extension?
-- Thanks for any information in advance.

**Comment by vchlum** [comment]
Hi @DroWnThePoor ! I am sorry the extension does not support the older version of Gnome Shell... I will add the info to this Github page.

As far as I know, the direct possibility to control Philips hue lights from Linux is poor and that is why I started this project:-) In the case of installing QT framework version 6 on your system, you could try a standalone application [hue-qt](https://github.com/vchlum/hue-qt). It is similar to this extension. This is a work in progress but the basic lights controlling works. I have been busy, but once I will have time for it I am going to continue developing it. Keep in mind it is not finished yet.

**Comment by vchlum** [comment]
I will close this issue now as I do not intend to provide compatibility with old Gnome shell versions... Sorry.
