### ISSUE TITLE
[Feature request] Ability to add different notification lights based on keywords 

### ISSUE THREAD

**Issue by alukortti** [vchlum/hue-lights#41]
Hey,

I just downloaded your extension and it works great right out of the box and I really like notification lights feature!

One thing that came into my mind regarding this right away was extension to this feature so I could add some keywords for different notification light colors.

For example:
Default notification color: Blue

If notification contains keyword ['Fail','Failed','Error'... etc]
Notification color: Red

If notification contains keyword ['Slack']
Notification color: Orange

There could be some +-button next to Default notification lights where you could add additional colors and keywords for those lights.

I hope my explanation is clear enough but what do you think?

**Comment by vchlum** [comment]
Hi @alukortti ! Thank you for the idea. It seems possible. I will look into it. I think regex would be better instead of keywords.

**Comment by alukortti** [comment]
Cool! Send me a message if you implement this and I can help with the testing. :)

**Comment by vchlum** [comment]
Hi, @alukortti once again:-) Still here? I added this feature. You can test it on the main branch. Feedback would be appreciated.

**Comment by vchlum** [comment]
Closing this issue as done.
