### ISSUE TITLE
Buttons: Touch not working?

### ISSUE THREAD

**Issue by rduivenvoorde** [vchlum/hue-lights#43]
First thanks! For this, very funny to find it in the gnome extensions :-)

Not sure if it is only me, but I have 2 Lenovo laptops, both running Debian testing//Gnome/Gnome-shell version 41.3

On my X280 the buttons are working both with mouse AND with finger/touch 
But on the tiny ideapad D330-10IGM only mouse is working, all buttons fail (the menu's (little triangles) when using touch/fingers.

Only difference is that D330 is running 'Gnome'(/Wayland) and the X280 running 'Gnome on Xorg'

Others have this issue?

**Comment by vchlum** [comment]
Hi @rduivenvoorde , I can confirm this behavior. Touching works only on Xorg on my Zenbook, which I usually use. It does not work on Wayland. I will investigate.

**Comment by vchlum** [comment]
Tested on Gnome 43, Wayland and it works... but you need a stylus on smaller displays (or increase scaling):-) Anyway, touch issues are out of the scope of this gnome extension. It uses standard control components of gnome-shell.
