### ISSUE TITLE
System log get spammed with messages when connection drops

### ISSUE THREAD

**Issue by qlixed** [vchlum/hue-lights#47]
Once connection is established to the HUE hub and is lost the extensions start to spam the logs with the following message:

```
mar 21 13:38:06 pluma gnome-shell[26898]: Object .PhueSyncBoxMenu (0x55ed667ea300), has been already disposed — impossible to set any property on it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
mar 21 13:38:06 pluma gnome-shell[26898]: == Stack trace for context 0x55ed60ed01e0 ==
mar 21 13:38:06 pluma gnome-shell[26898]: #0   55ed6b9296a8 i   /home/qlixed/.local/share/gnome-shell/extensions/hue-lights@chlumskyvaclav.gmail.com/phuepanelmenu.js:718 (152cbe56ce20 @ 105)
mar 21 13:38:06 pluma gnome-shell[26898]: #1   55ed6b9295c8 i   /home/qlixed/.local/share/gnome-shell/extensions/hue-lights@chlumskyvaclav.gmail.com/syncboxmenu.js:1113 (152cbe587c40 @ 61)
mar 21 13:38:06 pluma gnome-shell[26898]: #2   7ffec15ab600 b   /home/qlixed/.local/share/gnome-shell/extensions/hue-lights@chlumskyvaclav.gmail.com/syncboxmenu.js:1090 (152cbe587c90 @ 81)
```
This repeats around every 1 or 2 seconds (I think that is related to the timeout setting settable on the 'Advanced settings' section)
This not happens if the extension starts and connection can't be done the first time.

**Comment by vchlum** [comment]
Thank you, fixed.

**Comment by chrbkr** [comment]
Apperently, the issue (or a similar one) has reappeared:

    Jun 24 21:02:51 manjaro NetworkManager[993]: <info>  [1719255771.5011] device (ppp0): state change: disconnected -> unmanaged (reason 'unmanaged', sys-iface-state: 'removed')
    Jun 24 21:02:51 manjaro gnome-shell[2219]: Object St.BoxLayout (0x55ce1f876df0), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
                                                == Stack trace for context 0x55ce1b74b290 ==
                                                #0   7ffc7008be40 b   resource:///org/gnome/shell/ui/popupMenu.js:828 (33fe1eaf58d0 @ 22)
                                                #1   55ce1b8138e8 i   file:///home/chrbkr/.local/share/gnome-shell/extensions/hue-lights@chlumskyvaclav.gmail.com/phuepanelmenu.js:663 (35f21d0fd560 @ 85)
                                                #2   55ce1b813838 i   file:///home/chrbkr/.local/share/gnome-shell/extensions/hue-lights@chlumskyvaclav.gmail.com/extensionmenu.js:4832 (35f21d033830 @ 32)
                                                #3   55ce1b8137b8 i   file:///home/chrbkr/.local/share/gnome-shell/extensions/hue-lights@chlumskyvaclav.gmail.com/extensionmenu.js:141 (35f21d0154c0 @ 12)
                                                #4   55ce1b813728 i   resource:///org/gnome/shell/ui/init.js:21 (33fe1ea70bf0 @ 48)
    Jun 24 21:02:51 manjaro gnome-shell[2219]: Object .PhueMenu (0x55ce1f29e740), has been already disposed — impossible to set any property on it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
                                                == Stack trace for context 0x55ce1b74b290 ==
                                                #0   55ce1b8138e8 i   file:///home/chrbkr/.local/share/gnome-shell/extensions/hue-lights@chlumskyvaclav.gmail.com/phuepanelmenu.js:821 (35f21d0fd6a0 @ 821)
                                                #1   55ce1b813838 i   file:///home/chrbkr/.local/share/gnome-shell/extensions/hue-lights@chlumskyvaclav.gmail.com/extensionmenu.js:4836 (35f21d033830 @ 90)
                                                #2   55ce1b8137b8 i   file:///home/chrbkr/.local/share/gnome-shell/extensions/hue-lights@chlumskyvaclav.gmail.com/extensionmenu.js:141 (35f21d0154c0 @ 12)
                                                #3   55ce1b813728 i   resource:///org/gnome/shell/ui/init.js:21 (33fe1ea70bf0 @ 48)
`
