### ISSUE TITLE
Icons look weird

### ISSUE THREAD

**Issue by remcohaszing** [vchlum/hue-lights#54]
First of all: This is one of my favourite GNOME extensions! Thank you for making this!

On my system the icons look a bit weird. It looks like it’s having issues with the transparent parts. The icons look much better in the screenshot example in this project’s readme.

![image](https://user-images.githubusercontent.com/779047/192100776-74d4aa3b-4a05-4073-afbf-6d7d3d91cacd.png)

I don’t have this issue with other extensions or parts of GNOME.

![image](https://user-images.githubusercontent.com/779047/192100953-9ffb6aff-2490-43b6-8312-6c0031ba9eae.png)

I don’t recall whether this issue has always existed for me or not. Any idea what could be causing this? Is this a bug in the extension?

**Comment by vchlum** [comment]
Hi! Me icons are sharp. This is not correct. I tuned up the blur of the icons in the early versions of the extension. No recent changes. I believe I know what it could be... I will look into it. I do not know how to reproduce your issue yet. What is your desktop scaling, resolution, and Linux distribution, please?

**Comment by remcohaszing** [comment]
My laptop is a System76 Oryx Pro running Pop!_OS 22.04. The resolution of my laptop screen is 1920x1080. I mostly have 2 additional monitors on leading to a total resolution of 3840x2160. The desktop scaling is 100%.

![GNOME display settings](https://user-images.githubusercontent.com/779047/192981913-532c66b0-e81d-4bbd-8c99-4f9bdf86387b.png)

**Comment by vchlum** [comment]
I can not reproduce it in the VirtualBox instance yet. Could you please try the attached patch [contrast.txt](https://github.com/vchlum/hue-lights/files/9676456/contrast.txt) ?
`patch $HOME/.local/share/gnome-shell/extensions/hue-lights@chlumskyvaclav.gmail.com/phuepanelmenu.js contrast.txt`
Please, log out and log back in after patching...

**Comment by remcohaszing** [comment]
I applied it and did a full reboot just to be sure. Unfortunately this didn’t make a difference. I also made sure the patch is applied correctly by looking into the patched file, and it is.

**Comment by vchlum** [comment]
Hi again! I found out ... I hope:-) Do you use this extension?: https://extensions.gnome.org/extension/2878/transparent-top-panel/ Could you try to disable it?

**Comment by vchlum** [comment]
The extension 'Transparent Top Panel' can not deal with SVG icons. The extension also causes the odd background of icons representing GTK extendable menu items:
![image](https://user-images.githubusercontent.com/16756616/193871876-4d3320b8-7465-400d-85d6-91884c0bcc5d.png)

**Comment by remcohaszing** [comment]
I do use that extension! And disabling it fixed the issue. Thanks for figuring that out! I was using that extension to get a transparent / black top panel. It’s not **that** important to me, so I’ll just disable it.

**Comment by vchlum** [comment]
Glad we got this. :-) I am closing this issue as solved. I do not intend to change the icon format.
