### ISSUE TITLE
The associated connections do not work anymore

### ISSUE THREAD

**Issue by jazzzz** [vchlum/hue-lights#55]
Since commit a23cefa84e1be3211d7ddb7661c867cc333efec6, the icon does not show anymore in the panel. The extension is correctly enabled with no error, the settings can be opened from the extension manager, but the icon does not appear.

It looks like the network is not correctly detected because I see this in the debug log: Hue Lights [debug]: Bridge 001788fffe21bbfe is available but it prefers another network.

**Comment by vchlum** [comment]
Hi, what is your gnome version, please? Anyway, try to run this command:
`dconf reset /org/gnome/shell/extensions/hue-lights/associated-connection`
It should reset related settings. Did it help?

**Comment by vchlum** [comment]
Oh, sorry the gnome version is in the title... My mistake. I will investigate.

**Comment by jazzzz** [comment]
> Anyway, try to run this command:
> `dconf reset /org/gnome/shell/extensions/hue-lights/associated-connection`
> It should reset related settings. Did it help?

Yes the icon shows up after this, but as soon as I try to re-associate the bridge with the current connection, it disappears.

**Comment by jazzzz** [comment]
I found the issue and fixed it in PR #56.
