### ISSUE TITLE
Question: Switch management

### ISSUE THREAD

**Issue by borgdylan** [vchlum/hue-lights#6]
I ahve discivered that the extenion lets me disable and enable hue dimmer switches. What are the percentages next o the switches, battery levels?

**Comment by vchlum** [comment]
Yes @borgdylan, it is the battery level. I will try to make it more obvious in the future (suggestion welcomed). I wanted to save space because in the case of motion sensor the line contains the light level, the temperature, and the battery level, which is plenty of data for one short line.

**Comment by borgdylan** [comment]
I'm glad I found out your extension then! I also found out local resellers of CR2450 batteries. One of my switches has 40% left.

**Comment by vchlum** [comment]
A new battery icon added to indicate the percentage purpose. Thank you for pointing out. Resolved.

**Comment by borgdylan** [comment]
Is the latest update going to be pushed to e.g.o or should I update manually?

**Comment by vchlum** [comment]
Sorry for the delay @borgdylan. I will submit it for review soon.
