### ISSUE TITLE
TypeError: this._positionInPanelComboBox is null

### ISSUE THREAD

**Issue by moxo26** [vchlum/hue-lights#60]
The settings of extension hue-lights@chlumskyvaclav.gmail.com had an error:
```
TypeError: this._positionInPanelComboBox is null
```

Stack trace:
```
_updateGeneral@/home/pacs/.local/share/gnome-shell/extensions/hue-lights@chlumskyvaclav.gmail.com/prefs.js:1758:9
_init@/home/pacs/.local/share/gnome-shell/extensions/hue-lights@chlumskyvaclav.gmail.com/prefs.js:1126:14
buildPrefsWidget@/home/pacs/.local/share/gnome-shell/extensions/hue-lights@chlumskyvaclav.gmail.com/prefs.js:1944:12
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:207:40
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:222:19
start@resource:///org/gnome/gjs/modules/script/package.js:206:5
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by vchlum** [comment]
Hi @moxo26 thank you for reporting. this._positionInPanelComboBox should be autogenerated by the GTK builder. Could you please share what version of gnome you use? Also, what is your Linux distribution?

**Comment by moxo26** [comment]
My GNOME version is 3.36.8
My linux distribution is Ubuntu 20.04.5 LTS

**Comment by vchlum** [comment]
I am sorry but as you can read in #58 the support for gnome < 40 was dropped. The last version of this extension supporting your system is 24. You can either check out tag 24 on the main branch or download it here https://extensions.gnome.org/extension/3737/hue-lights/ There will be no more new versions for old gnome versions.
