### ISSUE TITLE
Change brightness with scroll wheel

### ISSUE THREAD

**Issue by RichardFevrier** [vchlum/hue-lights#62]
Thanks for all of your work 🎉

Currently I can change the brightness by clicking on a scroll bar, or by dragging with the mouse.
When I use the scroll wheel, the scroll bar moves and the value shown changes, but the bulb brightness is not changed.

I think it has something to do with using the `drag-end` event instead of the `notify::value` one 🙂

**Comment by vchlum** [comment]
Hi @RichardFevrier ! I know:-) This is intentional. Using `notify::value` causes constantly changing lights, which invokes a lot of requests on the bridge and the scrolling is not smooth because it changes as it scrolls. We need here an event for the 'end of scrolling'. Any ideas?

**Comment by RichardFevrier** [comment]
Good point @vchlum !
Maybe [this event](https://docs.gtk.org/gtk4/signal.EventControllerScroll.scroll-end.html) would do the job?

**Comment by vchlum** [comment]
I remember now. I already found this event... a long some ago. It is not available on the slider component in the UI of gnome-shell. This extension uses this [slider](https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/main/js/ui/slider.js). As you can see, we have only `drag-begin` and `drag-end` here.

Now, the interesting thing is that volume can be controlled by mouse scrolling. Hmm.

**Comment by vchlum** [comment]
Done. Fixed. The scrolling will invoke the brightness change once per 500ms.
