### ISSUE TITLE
Notification icon is way bigger then all others

### ISSUE THREAD

**Issue by razzeee** [vchlum/hue-lights#64]
Is there a reason, that this icon has so much whitespace around it?

![image](https://user-images.githubusercontent.com/5943908/201327189-26d21fba-34ed-4053-b23b-e2f238628983.png)

![image](https://user-images.githubusercontent.com/5943908/201327226-05230c33-64ef-458e-a4cb-e0d0e55c84e5.png)

**Comment by vchlum** [comment]
I agree. The reason was the unset style. Space around panel icons reduced. Thank you. ![Snímek obrazovky z 2022-11-11 16-36-14](https://user-images.githubusercontent.com/16756616/201373696-44f7685c-3fc6-4f82-83ee-f2647ef66659.png)
