### ISSUE TITLE
API planned?

### ISSUE THREAD

**Issue by jqlifice** [vchlum/hue-lights#65]
Hi,
I am using your extension, which works great, thanks a lot!
While I was using windows I used to use my [StreamDeck](https://www.elgato.com/en/welcome-to-stream-deck) to control the lighting for my scenes.
While there is a community version of the [StreamDeck Software](https://github.com/timothycrosley/streamdeck-ui/) it does not include the plugins the Windows version had. 
As I would really love to have my hot keys for lighting back on the Deck, I was wondering if there was any sort of API planned or if you have any documentation which shows possible outside interactions, which I could call to change Lighting.

Thanks!

**Comment by vchlum** [comment]
Hi @jqlifice! I do not intend to add an API for controlling this extension. The only interface is the menu. I would suggest you search the Internet for e.g. hue python API or something similar. Although I did not try such an API, I know some exist...

**Comment by jqlifice** [comment]
Hi @vchlum 
thanks for the response, I was hoping to solve it just by shell commands and not having to write my own application, but Ill find a way to get it done. Thanks for your swift response!
