### ISSUE TITLE
The sliders are always black instead of the color of the lights

### ISSUE THREAD

**Issue by jazzzz** [vchlum/hue-lights#69]
Before:

![image](https://user-images.githubusercontent.com/290626/228964541-deadb1b3-6e31-45c8-b1f2-79946e295cba.png)

After:

![image](https://user-images.githubusercontent.com/290626/228963586-593e8a01-2e07-4f84-b0a8-c0c4f892c811.png)

Reverting the commit 07351994991d2547fa347bae82e0e63f548e334d fixes it.

**Comment by vchlum** [comment]
Fixed. Thank you!:-)
