### ISSUE TITLE
"Press bridge button and connect" text unclear

### ISSUE THREAD

**Issue by LadislavMalecek** [vchlum/hue-lights#7]
Suggestion/Bad design choice

I would say that the text on the connect to bridge button is not entirely user-proof. I would suggest adding a one more inbetween step where

1. Connect button
2. Alert window that tells the person to go to press the physical pairing button
3. Success message

Or at least some message saying what went wrong when the user presses the button without actually pressing the physical button on the device. I just thought that the extension itself is broken.

Extension version: 6

**Comment by vchlum** [comment]
Thank you @LadislavMalecek for pointing it out. FIxed. Not pressing the button, an alert will be shown. Also, the confusing button label is changed to "Connect".
