### ISSUE TITLE
Right clicking on a light broke the app

### ISSUE THREAD

**Issue by dysbulic** [vchlum/hue-lights#70]
I right clicked on one of my lights in the dropdown. It caused the color selector to open in the center of my screen & I can no longer click anything in the taskbar.

The color selector doesn't respond to the mouse & I cannot close it. I can alt-tab between windows, but can't select them with the mouse.

I see no obvious way to shut down the app.

I'm in Ubuntu 22.10 & I just installed the extension.

![Screenshot from 2023-07-07 08-47-35](https://github.com/vchlum/hue-lights/assets/181523/5b2d06ab-ec76-4571-b148-bf8343699b47)

**Comment by vchlum** [comment]
Hi @dysbulic ! Clicking on Finish should close the modal window. I can see it does not work reliably anymore... The button only works if it is not over another window :-(

The extension supports two different kinds of menus. You are using the standard menu, which is old and I do not recommend it anymore.

Please, as a workaround switch to 'Compact menu', press the item menu with your bridge name, and click on switch to compact menu.:
![image](https://github.com/vchlum/hue-lights/assets/16756616/881dd612-d67a-407b-9ef2-2aa7ef4e1ada)
I will probably remove the standard menu from the extension as the compact menu is much better.

**Comment by vchlum** [comment]
This is removed now. In the future relases, there will be only the compact menu.
