### ISSUE TITLE
Allow changing color of an entire zone at once

### ISSUE THREAD

**Issue by dysbulic** [vchlum/hue-lights#71]
It would be nice if we could trigger a color changer for a zone that sets all the lights within at once.

**Comment by vchlum** [comment]
It is possible. Use the compact menu as described #70 and click the room or zone - it will be selected. You can simply change the scene or color for all lights within the group.

**Comment by vchlum** [comment]
I am closing this. The standard menu will be removed (soon) in the Gnome 45 version anyway.
