### ISSUE TITLE
Very unresponsive

### ISSUE THREAD

**Issue by R-Sharafaldin** [vchlum/hue-lights#83]
I've had this extension installed for the longest time but not really used it. Trying to use it today reminded me of why. Wheneveri try to change colour, turn off/on a light, change scene or anything really, there's a huge delay up to 5 minutes or so, or no response at all. Tried generating a log, but it's completely empty.

**Comment by vchlum** [comment]
Hi @R-Sharafaldin . That is odd... Please, I have a few questions:
 * what is your system (version) and gnome version?
 * what version of hue-lights do you use? (early versions had performance issues...) are you on current 33?
 * could you provide a list of other extensions installed on your system?
 * do you use wifi or ethernet?
 * could you check the bridge timeout in settings? what is the value? (default is 2 ... after 2 seconds the connection should be lost - it is odd to have 5 minutes delay:-))

**Comment by vchlum** [comment]
I will close this as I suppose this was due to an older version of this extension.
