### ISSUE TITLE
Extension changes Gnome language settings

### ISSUE THREAD

**Issue by hmmSalat** [vchlum/hue-lights#9]
Hey,

I'm using this extension on Arch Linux with Gnome 3.38.2 on X11 and noticed that installing this extension changes some of the language settings in Gnome.

For example: I am using Gnome with german language settings. As soon as i install this extension some of the gnome menus appear in english when they are supposed to be in german. I've tried setting the Gnome language settings to english and back to german again. The problem still exists. After uninstalling this extension, everything works fine again.

regards,
hmmSalat

**Comment by vchlum** [comment]
Hi @hmmSalat, thank you for this report. Unfortunately, I can not reproduce this issue. I installed a fresh Arch Linux with Gnome 3.38.2 in my VirtualBox. I use the Czech language. I set the Czech language for the whole system. Could you please share which strings/menus/items are in English?

**Comment by hmmSalat** [comment]
Hey, thank you for your reply! In my case the right click desktop menu and the gnome menu in the top right corner (reboot, power off, wifi menu) are affected.

**Comment by vchlum** [comment]
Thanks, @hmmSalat. Issue confirmed and fixed.

**Comment by hmmSalat** [comment]
Thank you for taking your time to fix this issue :-) Great extension! :-)

**Comment by vchlum** [comment]
Version 8 has been released and submitted for review. Please install the version once it becomes available on e.g.o. I will close this issue now.
